// This file is generated by omniidl (C++ backend) - omniORB_4_2. Do not edit.

#include "banque.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_2_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::PR_structMember _0RL_structmember_banque_mSoldeInsuffisant[] = {
  {"solde", CORBA::TypeCode::PR_double_tc()},
  {"montant", CORBA::TypeCode::PR_double_tc()}
};

static CORBA::TypeCode_ptr _0RL_tc_banque_mSoldeInsuffisant = CORBA::TypeCode::PR_exception_tc("IDL:banque/SoldeInsuffisant:1.0", "SoldeInsuffisant", _0RL_structmember_banque_mSoldeInsuffisant, 2, &_0RL_tcTrack);
#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_SoldeInsuffisant = _0RL_tc_banque_mSoldeInsuffisant;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_SoldeInsuffisant = _0RL_tc_banque_mSoldeInsuffisant;
#endif


static CORBA::PR_structMember _0RL_structmember_banque_mCompteIntrouvable[] = {
  {"id", CORBA::TypeCode::PR_long_tc()}
};

static CORBA::TypeCode_ptr _0RL_tc_banque_mCompteIntrouvable = CORBA::TypeCode::PR_exception_tc("IDL:banque/CompteIntrouvable:1.0", "CompteIntrouvable", _0RL_structmember_banque_mCompteIntrouvable, 1, &_0RL_tcTrack);
#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_CompteIntrouvable = _0RL_tc_banque_mCompteIntrouvable;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_CompteIntrouvable = _0RL_tc_banque_mCompteIntrouvable;
#endif


static CORBA::PR_structMember _0RL_structmember_banque_mmouvementCompte[] = {
  {"id", CORBA::TypeCode::PR_long_tc()},
  {"montant", CORBA::TypeCode::PR_double_tc()}
};

#ifdef _0RL_tc_banque_mmouvementCompte
#  undef _0RL_tc_banque_mmouvementCompte
#endif
static CORBA::TypeCode_ptr _0RL_tc_banque_mmouvementCompte = CORBA::TypeCode::PR_struct_tc("IDL:banque/mouvementCompte:1.0", "mouvementCompte", _0RL_structmember_banque_mmouvementCompte, 2, &_0RL_tcTrack);

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_mouvementCompte = _0RL_tc_banque_mmouvementCompte;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_mouvementCompte = _0RL_tc_banque_mmouvementCompte;
#endif


static CORBA::PR_structMember _0RL_structmember_banque_mCompte[] = {
  {"id", CORBA::TypeCode::PR_long_tc()},
  {"titulaire", CORBA::TypeCode::PR_string_tc(0, &_0RL_tcTrack)},
  {"solde", CORBA::TypeCode::PR_double_tc()}
};

#ifdef _0RL_tc_banque_mCompte
#  undef _0RL_tc_banque_mCompte
#endif
static CORBA::TypeCode_ptr _0RL_tc_banque_mCompte = CORBA::TypeCode::PR_struct_tc("IDL:banque/Compte:1.0", "Compte", _0RL_structmember_banque_mCompte, 3, &_0RL_tcTrack);

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_Compte = _0RL_tc_banque_mCompte;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_Compte = _0RL_tc_banque_mCompte;
#endif






static CORBA::TypeCode_ptr _0RL_tc_banque_mListeComptes = CORBA::TypeCode::PR_alias_tc("IDL:banque/ListeComptes:1.0", "ListeComptes", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_banque_mCompte, &_0RL_tcTrack), &_0RL_tcTrack);


#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_ListeComptes = _0RL_tc_banque_mListeComptes;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_ListeComptes = _0RL_tc_banque_mListeComptes;
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_BanqueOperator = CORBA::TypeCode::PR_interface_tc("IDL:banque/BanqueOperator:1.0", "BanqueOperator", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_BanqueOperator = CORBA::TypeCode::PR_interface_tc("IDL:banque/BanqueOperator:1.0", "BanqueOperator", &_0RL_tcTrack);
#endif


static void _0RL_banque_mSoldeInsuffisant_marshal_fn(cdrStream& _s, void* _v)
{
  const banque::SoldeInsuffisant* _p = (const banque::SoldeInsuffisant*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mSoldeInsuffisant_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::SoldeInsuffisant* _p = new banque::SoldeInsuffisant;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mSoldeInsuffisant_destructor_fn(void* _v)
{
  banque::SoldeInsuffisant* _p = (banque::SoldeInsuffisant*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::SoldeInsuffisant& _s)
{
  banque::SoldeInsuffisant* _p = new banque::SoldeInsuffisant(_s);
  _a.PR_insert(_0RL_tc_banque_mSoldeInsuffisant,
               _0RL_banque_mSoldeInsuffisant_marshal_fn,
               _0RL_banque_mSoldeInsuffisant_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, const banque::SoldeInsuffisant* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mSoldeInsuffisant,
               _0RL_banque_mSoldeInsuffisant_marshal_fn,
               _0RL_banque_mSoldeInsuffisant_destructor_fn,
               (banque::SoldeInsuffisant*)_sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::SoldeInsuffisant*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mSoldeInsuffisant,
                    _0RL_banque_mSoldeInsuffisant_unmarshal_fn,
                    _0RL_banque_mSoldeInsuffisant_marshal_fn,
                    _0RL_banque_mSoldeInsuffisant_destructor_fn,
                    _v)) {
    _sp = (const banque::SoldeInsuffisant*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_insertToAny__cbanque_mSoldeInsuffisant(::CORBA::Any& _a, const ::CORBA::Exception& _e) {
  const banque::SoldeInsuffisant & _ex = (const banque::SoldeInsuffisant &) _e;
  operator<<=(_a,_ex);
}

static void _0RL_insertToAnyNCP__cbanque_mSoldeInsuffisant (::CORBA::Any& _a, const ::CORBA::Exception* _e) {
  const banque::SoldeInsuffisant* _ex = (const banque::SoldeInsuffisant*) _e;
  operator<<=(_a,_ex);
}

class _0RL_insertToAny_Singleton__cbanque_mSoldeInsuffisant {
public:
  _0RL_insertToAny_Singleton__cbanque_mSoldeInsuffisant() {
    banque::SoldeInsuffisant::insertToAnyFn = _0RL_insertToAny__cbanque_mSoldeInsuffisant;
    banque::SoldeInsuffisant::insertToAnyFnNCP = _0RL_insertToAnyNCP__cbanque_mSoldeInsuffisant;
  }
};
static _0RL_insertToAny_Singleton__cbanque_mSoldeInsuffisant _0RL_insertToAny_Singleton__cbanque_mSoldeInsuffisant_;


static void _0RL_banque_mCompteIntrouvable_marshal_fn(cdrStream& _s, void* _v)
{
  const banque::CompteIntrouvable* _p = (const banque::CompteIntrouvable*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mCompteIntrouvable_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::CompteIntrouvable* _p = new banque::CompteIntrouvable;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mCompteIntrouvable_destructor_fn(void* _v)
{
  banque::CompteIntrouvable* _p = (banque::CompteIntrouvable*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::CompteIntrouvable& _s)
{
  banque::CompteIntrouvable* _p = new banque::CompteIntrouvable(_s);
  _a.PR_insert(_0RL_tc_banque_mCompteIntrouvable,
               _0RL_banque_mCompteIntrouvable_marshal_fn,
               _0RL_banque_mCompteIntrouvable_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, const banque::CompteIntrouvable* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mCompteIntrouvable,
               _0RL_banque_mCompteIntrouvable_marshal_fn,
               _0RL_banque_mCompteIntrouvable_destructor_fn,
               (banque::CompteIntrouvable*)_sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::CompteIntrouvable*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mCompteIntrouvable,
                    _0RL_banque_mCompteIntrouvable_unmarshal_fn,
                    _0RL_banque_mCompteIntrouvable_marshal_fn,
                    _0RL_banque_mCompteIntrouvable_destructor_fn,
                    _v)) {
    _sp = (const banque::CompteIntrouvable*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_insertToAny__cbanque_mCompteIntrouvable(::CORBA::Any& _a, const ::CORBA::Exception& _e) {
  const banque::CompteIntrouvable & _ex = (const banque::CompteIntrouvable &) _e;
  operator<<=(_a,_ex);
}

static void _0RL_insertToAnyNCP__cbanque_mCompteIntrouvable (::CORBA::Any& _a, const ::CORBA::Exception* _e) {
  const banque::CompteIntrouvable* _ex = (const banque::CompteIntrouvable*) _e;
  operator<<=(_a,_ex);
}

class _0RL_insertToAny_Singleton__cbanque_mCompteIntrouvable {
public:
  _0RL_insertToAny_Singleton__cbanque_mCompteIntrouvable() {
    banque::CompteIntrouvable::insertToAnyFn = _0RL_insertToAny__cbanque_mCompteIntrouvable;
    banque::CompteIntrouvable::insertToAnyFnNCP = _0RL_insertToAnyNCP__cbanque_mCompteIntrouvable;
  }
};
static _0RL_insertToAny_Singleton__cbanque_mCompteIntrouvable _0RL_insertToAny_Singleton__cbanque_mCompteIntrouvable_;

static void _0RL_banque_mmouvementCompte_marshal_fn(cdrStream& _s, void* _v)
{
  banque::mouvementCompte* _p = (banque::mouvementCompte*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mmouvementCompte_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::mouvementCompte* _p = new banque::mouvementCompte;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mmouvementCompte_destructor_fn(void* _v)
{
  banque::mouvementCompte* _p = (banque::mouvementCompte*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::mouvementCompte& _s)
{
  banque::mouvementCompte* _p = new banque::mouvementCompte(_s);
  _a.PR_insert(_0RL_tc_banque_mmouvementCompte,
               _0RL_banque_mmouvementCompte_marshal_fn,
               _0RL_banque_mmouvementCompte_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, banque::mouvementCompte* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mmouvementCompte,
               _0RL_banque_mmouvementCompte_marshal_fn,
               _0RL_banque_mmouvementCompte_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::mouvementCompte*& _sp)
{
  return _a >>= (const banque::mouvementCompte*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::mouvementCompte*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mmouvementCompte,
                    _0RL_banque_mmouvementCompte_unmarshal_fn,
                    _0RL_banque_mmouvementCompte_marshal_fn,
                    _0RL_banque_mmouvementCompte_destructor_fn,
                    _v)) {
    _sp = (const banque::mouvementCompte*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_banque_mCompte_marshal_fn(cdrStream& _s, void* _v)
{
  banque::Compte* _p = (banque::Compte*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mCompte_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::Compte* _p = new banque::Compte;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mCompte_destructor_fn(void* _v)
{
  banque::Compte* _p = (banque::Compte*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::Compte& _s)
{
  banque::Compte* _p = new banque::Compte(_s);
  _a.PR_insert(_0RL_tc_banque_mCompte,
               _0RL_banque_mCompte_marshal_fn,
               _0RL_banque_mCompte_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, banque::Compte* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mCompte,
               _0RL_banque_mCompte_marshal_fn,
               _0RL_banque_mCompte_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::Compte*& _sp)
{
  return _a >>= (const banque::Compte*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::Compte*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mCompte,
                    _0RL_banque_mCompte_unmarshal_fn,
                    _0RL_banque_mCompte_marshal_fn,
                    _0RL_banque_mCompte_destructor_fn,
                    _v)) {
    _sp = (const banque::Compte*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_banque_mListeComptes_marshal_fn(cdrStream& _s, void* _v)
{
  banque::ListeComptes* _p = (banque::ListeComptes*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mListeComptes_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::ListeComptes* _p = new banque::ListeComptes;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mListeComptes_destructor_fn(void* _v)
{
  banque::ListeComptes* _p = (banque::ListeComptes*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::ListeComptes& _s)
{
  banque::ListeComptes* _p = new banque::ListeComptes(_s);
  _a.PR_insert(_0RL_tc_banque_mListeComptes,
               _0RL_banque_mListeComptes_marshal_fn,
               _0RL_banque_mListeComptes_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, banque::ListeComptes* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mListeComptes,
               _0RL_banque_mListeComptes_marshal_fn,
               _0RL_banque_mListeComptes_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::ListeComptes*& _sp)
{
  return _a >>= (const banque::ListeComptes*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::ListeComptes*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mListeComptes,
                    _0RL_banque_mListeComptes_unmarshal_fn,
                    _0RL_banque_mListeComptes_marshal_fn,
                    _0RL_banque_mListeComptes_destructor_fn,
                    _v)) {
    _sp = (const banque::ListeComptes*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_banque_mBanqueOperator_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_banque_mBanqueOperator_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(banque::BanqueOperator::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_banque_mBanqueOperator_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, banque::BanqueOperator_ptr _o)
{
  banque::BanqueOperator_ptr _no = banque::BanqueOperator::_duplicate(_o);
  _a.PR_insert(banque::_tc_BanqueOperator,
               _0RL_banque_mBanqueOperator_marshal_fn,
               _0RL_banque_mBanqueOperator_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, banque::BanqueOperator_ptr* _op)
{
  _a.PR_insert(banque::_tc_BanqueOperator,
               _0RL_banque_mBanqueOperator_marshal_fn,
               _0RL_banque_mBanqueOperator_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = banque::BanqueOperator::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::BanqueOperator_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(banque::_tc_BanqueOperator,
                    _0RL_banque_mBanqueOperator_unmarshal_fn,
                    _0RL_banque_mBanqueOperator_marshal_fn,
                    _0RL_banque_mBanqueOperator_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (banque::BanqueOperator_ptr)_r->_ptrToObjRef(banque::BanqueOperator::_PD_repoId);
    else
      _o = banque::BanqueOperator::_nil();
    return 1;
  }
  return 0;
}

