// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __banque_hh__
#define __banque_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_banque
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_banque
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_banque
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE banque

_CORBA_MODULE_BEG

  struct Compte {
    typedef _CORBA_ConstrType_Variable_Var<Compte> _var_type;

    
    ::CORBA::Long id;

    ::CORBA::String_member titulaire;

    ::CORBA::Double solde;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Compte::_var_type Compte_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Compte,Compte_var > Compte_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Compte;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ListeComptes;

  class ListeComptes_var;

  class ListeComptes : public _CORBA_Unbounded_Sequence< Compte >  {
  public:
    typedef ListeComptes_var _var_type;
    inline ListeComptes() {}
    inline ListeComptes(const ListeComptes& _s)
      : _CORBA_Unbounded_Sequence< Compte > (_s) {}

    inline ListeComptes(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence< Compte > (_max) {}
    inline ListeComptes(_CORBA_ULong _max, _CORBA_ULong _len, Compte* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence< Compte > (_max, _len, _val, _rel) {}

  

    inline ListeComptes& operator = (const ListeComptes& _s) {
      _CORBA_Unbounded_Sequence< Compte > ::operator=(_s);
      return *this;
    }
  };

  class ListeComptes_out;

  class ListeComptes_var {
  public:
    inline ListeComptes_var() : _pd_seq(0) {}
    inline ListeComptes_var(ListeComptes* _s) : _pd_seq(_s) {}
    inline ListeComptes_var(const ListeComptes_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ListeComptes(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ListeComptes_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ListeComptes_var& operator = (ListeComptes* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ListeComptes_var& operator = (const ListeComptes_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new ListeComptes;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline Compte& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ListeComptes* operator -> () { return _pd_seq; }
    inline const ListeComptes* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ListeComptes& () const { return *_pd_seq; }
#else
    inline operator const ListeComptes& () const { return *_pd_seq; }
    inline operator ListeComptes& () { return *_pd_seq; }
#endif
      
    inline const ListeComptes& in() const { return *_pd_seq; }
    inline ListeComptes&       inout()    { return *_pd_seq; }
    inline ListeComptes*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ListeComptes* _retn() { ListeComptes* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ListeComptes_out;
    
  private:
    ListeComptes* _pd_seq;
  };

  class ListeComptes_out {
  public:
    inline ListeComptes_out(ListeComptes*& _s) : _data(_s) { _data = 0; }
    inline ListeComptes_out(ListeComptes_var& _s)
      : _data(_s._pd_seq) { _s = (ListeComptes*) 0; }
    inline ListeComptes_out(const ListeComptes_out& _s) : _data(_s._data) {}
    inline ListeComptes_out& operator = (const ListeComptes_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ListeComptes_out& operator = (ListeComptes* _s) {
      _data = _s;
      return *this;
    }
    inline operator ListeComptes*&()  { return _data; }
    inline ListeComptes*& ptr()       { return _data; }
    inline ListeComptes* operator->() { return _data; }

    inline Compte& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ListeComptes*& _data;

  private:
    ListeComptes_out();
    ListeComptes_out& operator=(const ListeComptes_var&);
  };

  class ErreurBanque : public ::CORBA::UserException {
  public:
    
    ::CORBA::String_member message;

  

    inline ErreurBanque() {
      pd_insertToAnyFn    = insertToAnyFn;
      pd_insertToAnyFnNCP = insertToAnyFnNCP;
    }
    ErreurBanque(const ErreurBanque&);
    ErreurBanque(const char* i_message);
    ErreurBanque& operator=(const ErreurBanque&);
    virtual ~ErreurBanque();
    virtual void _raise() const;
    static ErreurBanque* _downcast(::CORBA::Exception*);
    static const ErreurBanque* _downcast(const ::CORBA::Exception*);
    static inline ErreurBanque* _narrow(::CORBA::Exception* _e) {
      return _downcast(_e);
    }
    
    void operator>>=(cdrStream&) const ;
    void operator<<=(cdrStream&) ;

    static _core_attr insertExceptionToAny    insertToAnyFn;
    static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

    virtual ::CORBA::Exception* _NP_duplicate() const;

    static _core_attr const char* _PD_repoId;
    static _core_attr const char* _PD_typeId;

  private:
    virtual const char* _NP_typeId() const;
    virtual const char* _NP_repoId(int*) const;
    virtual void _NP_marshal(cdrStream&) const;
  };

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ErreurBanque;

#ifndef __banque_mAudit__
#define __banque_mAudit__
  class Audit;
  class _objref_Audit;
  class _impl_Audit;
  
  typedef _objref_Audit* Audit_ptr;
  typedef Audit_ptr AuditRef;

  class Audit_Helper {
  public:
    typedef Audit_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Audit, Audit_Helper> Audit_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Audit,Audit_Helper > Audit_out;

#endif

  // interface Audit
  class Audit {
  public:
    // Declarations for this interface type.
    typedef Audit_ptr _ptr_type;
    typedef Audit_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Audit :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void journaliser(const char* operation, const char* details);

    // Constructors
    inline _objref_Audit()  { _PR_setobj(0); }  // nil
    _objref_Audit(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Audit();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Audit(const _objref_Audit&);
    _objref_Audit& operator = (const _objref_Audit&);
    // not implemented

    friend class Audit;
  };

  class _pof_Audit : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Audit() : _OMNI_NS(proxyObjectFactory)(Audit::_PD_repoId) {}
    virtual ~_pof_Audit();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Audit :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Audit();

    virtual void journaliser(const char* operation, const char* details) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Audit;

#ifndef __banque_mServiceBanque__
#define __banque_mServiceBanque__
  class ServiceBanque;
  class _objref_ServiceBanque;
  class _impl_ServiceBanque;
  
  typedef _objref_ServiceBanque* ServiceBanque_ptr;
  typedef ServiceBanque_ptr ServiceBanqueRef;

  class ServiceBanque_Helper {
  public:
    typedef ServiceBanque_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ServiceBanque, ServiceBanque_Helper> ServiceBanque_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ServiceBanque,ServiceBanque_Helper > ServiceBanque_out;

#endif

  // interface ServiceBanque
  class ServiceBanque {
  public:
    // Declarations for this interface type.
    typedef ServiceBanque_ptr _ptr_type;
    typedef ServiceBanque_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ServiceBanque :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Long creerCompte(const char* titulaire, ::CORBA::Double soldeInitial);
    ::CORBA::Double consulterSolde(::CORBA::Long idCompte);
    void deposer(::CORBA::Long idCompte, ::CORBA::Double montant);
    void retirer(::CORBA::Long idCompte, ::CORBA::Double montant);
    void virement(::CORBA::Long source, ::CORBA::Long destination, ::CORBA::Double montant);
    ListeComptes* listerComptes();

    // Constructors
    inline _objref_ServiceBanque()  { _PR_setobj(0); }  // nil
    _objref_ServiceBanque(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ServiceBanque();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ServiceBanque(const _objref_ServiceBanque&);
    _objref_ServiceBanque& operator = (const _objref_ServiceBanque&);
    // not implemented

    friend class ServiceBanque;
  };

  class _pof_ServiceBanque : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ServiceBanque() : _OMNI_NS(proxyObjectFactory)(ServiceBanque::_PD_repoId) {}
    virtual ~_pof_ServiceBanque();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ServiceBanque :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ServiceBanque();

    virtual ::CORBA::Long creerCompte(const char* titulaire, ::CORBA::Double soldeInitial) = 0;
    virtual ::CORBA::Double consulterSolde(::CORBA::Long idCompte) = 0;
    virtual void deposer(::CORBA::Long idCompte, ::CORBA::Double montant) = 0;
    virtual void retirer(::CORBA::Long idCompte, ::CORBA::Double montant) = 0;
    virtual void virement(::CORBA::Long source, ::CORBA::Long destination, ::CORBA::Double montant) = 0;
    virtual ListeComptes* listerComptes() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ServiceBanque;

_CORBA_MODULE_END



_CORBA_MODULE POA_banque
_CORBA_MODULE_BEG

  class Audit :
    public virtual banque::_impl_Audit,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Audit();

    inline ::banque::Audit_ptr _this() {
      return (::banque::Audit_ptr) _do_this(::banque::Audit::_PD_repoId);
    }
  };

  class ServiceBanque :
    public virtual banque::_impl_ServiceBanque,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ServiceBanque();

    inline ::banque::ServiceBanque_ptr _this() {
      return (::banque::ServiceBanque_ptr) _do_this(::banque::ServiceBanque::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_banque
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const banque::Compte& _s);
extern void operator<<=(::CORBA::Any& _a, banque::Compte* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, banque::Compte*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const banque::Compte*& _sp);

void operator<<=(::CORBA::Any& _a, const banque::ListeComptes& _s);
void operator<<=(::CORBA::Any& _a, banque::ListeComptes* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, banque::ListeComptes*& _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const banque::ListeComptes*& _sp);

void operator<<=(::CORBA::Any& _a, const banque::ErreurBanque& _s);
void operator<<=(::CORBA::Any& _a, const banque::ErreurBanque* _sp);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const banque::ErreurBanque*& _sp);

void operator<<=(::CORBA::Any& _a, banque::Audit_ptr _s);
void operator<<=(::CORBA::Any& _a, banque::Audit_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, banque::Audit_ptr& _s);

void operator<<=(::CORBA::Any& _a, banque::ServiceBanque_ptr _s);
void operator<<=(::CORBA::Any& _a, banque::ServiceBanque_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, banque::ServiceBanque_ptr& _s);



inline void
banque::Audit::_marshalObjRef(::banque::Audit_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
banque::ServiceBanque::_marshalObjRef(::banque::ServiceBanque_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_banque
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_banque
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_banque
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_banque
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_banque
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_banque
#endif

#endif  // __banque_hh__

