// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "banque.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



::CORBA::Exception::insertExceptionToAny banque::SoldeInsuffisant::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP banque::SoldeInsuffisant::insertToAnyFnNCP = 0;

banque::SoldeInsuffisant::SoldeInsuffisant(const banque::SoldeInsuffisant& _s) : ::CORBA::UserException(_s)
{
  solde = _s.solde;
  montant = _s.montant;

}

banque::SoldeInsuffisant::SoldeInsuffisant(::CORBA::Double _solde, ::CORBA::Double _montant)
{
  pd_insertToAnyFn    = banque::SoldeInsuffisant::insertToAnyFn;
  pd_insertToAnyFnNCP = banque::SoldeInsuffisant::insertToAnyFnNCP;
  solde = _solde;
  montant = _montant;

}



banque::SoldeInsuffisant& banque::SoldeInsuffisant::operator=(const banque::SoldeInsuffisant& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    solde = _s.solde;
    montant = _s.montant;

  }
  return *this;
}

banque::SoldeInsuffisant::~SoldeInsuffisant() {}

void banque::SoldeInsuffisant::_raise() const { throw *this; }

const char* banque::SoldeInsuffisant::_PD_repoId = "IDL:banque/SoldeInsuffisant:1.0";
const char* banque::SoldeInsuffisant::_PD_typeId = "Exception/UserException/banque::SoldeInsuffisant";

banque::SoldeInsuffisant* banque::SoldeInsuffisant::_downcast(::CORBA::Exception* _e) {
  return (SoldeInsuffisant*) _NP_is_a(_e, _PD_typeId);
}

const banque::SoldeInsuffisant* banque::SoldeInsuffisant::_downcast(const ::CORBA::Exception* _e) {
  return (const SoldeInsuffisant*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* banque::SoldeInsuffisant::_NP_duplicate() const {
  return new SoldeInsuffisant(*this);
}

const char* banque::SoldeInsuffisant::_NP_typeId() const {
  return _PD_typeId;
}

const char* banque::SoldeInsuffisant::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:banque/SoldeInsuffisant:1.0");
  return _PD_repoId;
}
 
void banque::SoldeInsuffisant::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
banque::SoldeInsuffisant::operator>>= (cdrStream& _n) const
{
  solde >>= _n;
  montant >>= _n;

}

void
banque::SoldeInsuffisant::operator<<= (cdrStream& _n)
{
  (::CORBA::Double&)solde <<= _n;
  (::CORBA::Double&)montant <<= _n;

}

::CORBA::Exception::insertExceptionToAny banque::CompteIntrouvable::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP banque::CompteIntrouvable::insertToAnyFnNCP = 0;

banque::CompteIntrouvable::CompteIntrouvable(const banque::CompteIntrouvable& _s) : ::CORBA::UserException(_s)
{
  id = _s.id;

}

banque::CompteIntrouvable::CompteIntrouvable(::CORBA::Long _id)
{
  pd_insertToAnyFn    = banque::CompteIntrouvable::insertToAnyFn;
  pd_insertToAnyFnNCP = banque::CompteIntrouvable::insertToAnyFnNCP;
  id = _id;

}



banque::CompteIntrouvable& banque::CompteIntrouvable::operator=(const banque::CompteIntrouvable& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    id = _s.id;

  }
  return *this;
}

banque::CompteIntrouvable::~CompteIntrouvable() {}

void banque::CompteIntrouvable::_raise() const { throw *this; }

const char* banque::CompteIntrouvable::_PD_repoId = "IDL:banque/CompteIntrouvable:1.0";
const char* banque::CompteIntrouvable::_PD_typeId = "Exception/UserException/banque::CompteIntrouvable";

banque::CompteIntrouvable* banque::CompteIntrouvable::_downcast(::CORBA::Exception* _e) {
  return (CompteIntrouvable*) _NP_is_a(_e, _PD_typeId);
}

const banque::CompteIntrouvable* banque::CompteIntrouvable::_downcast(const ::CORBA::Exception* _e) {
  return (const CompteIntrouvable*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* banque::CompteIntrouvable::_NP_duplicate() const {
  return new CompteIntrouvable(*this);
}

const char* banque::CompteIntrouvable::_NP_typeId() const {
  return _PD_typeId;
}

const char* banque::CompteIntrouvable::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:banque/CompteIntrouvable:1.0");
  return _PD_repoId;
}
 
void banque::CompteIntrouvable::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
banque::CompteIntrouvable::operator>>= (cdrStream& _n) const
{
  id >>= _n;

}

void
banque::CompteIntrouvable::operator<<= (cdrStream& _n)
{
  (::CORBA::Long&)id <<= _n;

}

void
banque::mouvementCompte::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  montant >>= _n;

}

void
banque::mouvementCompte::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  (::CORBA::Double&)montant <<= _n;

}

void
banque::Compte::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(titulaire,0);
  solde >>= _n;

}

void
banque::Compte::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  titulaire = _n.unmarshalString(0);
  (::CORBA::Double&)solde <<= _n;

}

banque::BanqueOperator_ptr banque::BanqueOperator_Helper::_nil() {
  return ::banque::BanqueOperator::_nil();
}

::CORBA::Boolean banque::BanqueOperator_Helper::is_nil(::banque::BanqueOperator_ptr p) {
  return ::CORBA::is_nil(p);

}

void banque::BanqueOperator_Helper::release(::banque::BanqueOperator_ptr p) {
  ::CORBA::release(p);
}

void banque::BanqueOperator_Helper::marshalObjRef(::banque::BanqueOperator_ptr obj, cdrStream& s) {
  ::banque::BanqueOperator::_marshalObjRef(obj, s);
}

banque::BanqueOperator_ptr banque::BanqueOperator_Helper::unmarshalObjRef(cdrStream& s) {
  return ::banque::BanqueOperator::_unmarshalObjRef(s);
}

void banque::BanqueOperator_Helper::duplicate(::banque::BanqueOperator_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

banque::BanqueOperator_ptr
banque::BanqueOperator::_duplicate(::banque::BanqueOperator_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

banque::BanqueOperator_ptr
banque::BanqueOperator::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


banque::BanqueOperator_ptr
banque::BanqueOperator::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

banque::BanqueOperator_ptr
banque::BanqueOperator::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_BanqueOperator _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_BanqueOperator* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_BanqueOperator;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* banque::BanqueOperator::_PD_repoId = "IDL:banque/BanqueOperator:1.0";


banque::_objref_BanqueOperator::~_objref_BanqueOperator() {
  
}


banque::_objref_BanqueOperator::_objref_BanqueOperator(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::banque::BanqueOperator::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
banque::_objref_BanqueOperator::_ptrToObjRef(const char* id)
{
  if (id == ::banque::BanqueOperator::_PD_repoId)
    return (::banque::BanqueOperator_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::banque::BanqueOperator::_PD_repoId))
    return (::banque::BanqueOperator_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for banque::BanqueOperator::getSolde

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_clong_e_cbanque_mCompteIntrouvable
class _0RL_cd_be1b0533d67a6407_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_be1b0533d67a6407_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_be1b0533d67a6407_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_be1b0533d67a6407_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_be1b0533d67a6407_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_be1b0533d67a6407_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_be1b0533d67a6407_00000000::_user_exns[] = {
  banque::CompteIntrouvable::_PD_repoId
};

void _0RL_cd_be1b0533d67a6407_00000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::CompteIntrouvable::_PD_repoId)) {
    banque::CompteIntrouvable _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_be1b0533d67a6407_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_be1b0533d67a6407_00000000* tcd = (_0RL_cd_be1b0533d67a6407_00000000*)cd;
  banque::_impl_BanqueOperator* impl = (banque::_impl_BanqueOperator*) svnt->_ptrToInterface(banque::BanqueOperator::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->getSolde(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->getSolde(tcd->arg_0);
  else {
    try {
      tcd->result = impl->getSolde(tcd->arg_0);
    }
    catch(banque::CompteIntrouvable& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double banque::_objref_BanqueOperator::getSolde(::CORBA::Long id)
{
  _0RL_cd_be1b0533d67a6407_00000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_10000000, "getSolde", 9);
  _call_desc.arg_0 = id;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for banque::BanqueOperator::effectuerOperation

// Proxy call descriptor class. Mangled signature:
//  void_i_cdouble_i_clong_e_cbanque_mSoldeInsuffisant
class _0RL_cd_be1b0533d67a6407_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_be1b0533d67a6407_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Long arg_1;
};

void _0RL_cd_be1b0533d67a6407_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_be1b0533d67a6407_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

const char* const _0RL_cd_be1b0533d67a6407_20000000::_user_exns[] = {
  banque::SoldeInsuffisant::_PD_repoId
};

void _0RL_cd_be1b0533d67a6407_20000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::SoldeInsuffisant::_PD_repoId)) {
    banque::SoldeInsuffisant _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_be1b0533d67a6407_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_be1b0533d67a6407_20000000* tcd = (_0RL_cd_be1b0533d67a6407_20000000*)cd;
  banque::_impl_BanqueOperator* impl = (banque::_impl_BanqueOperator*) svnt->_ptrToInterface(banque::BanqueOperator::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  impl->effectuerOperation(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    impl->effectuerOperation(tcd->arg_0, tcd->arg_1);
  else {
    try {
      impl->effectuerOperation(tcd->arg_0, tcd->arg_1);
    }
    catch(banque::SoldeInsuffisant& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void banque::_objref_BanqueOperator::effectuerOperation(::CORBA::Double montant, ::CORBA::Long id)
{
  _0RL_cd_be1b0533d67a6407_20000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_30000000, "effectuerOperation", 19);
  _call_desc.arg_0 = montant;
  _call_desc.arg_1 = id;

  _invoke(_call_desc);



}


//
// Code for banque::BanqueOperator::listerComptes

// Proxy call descriptor class. Mangled signature:
//  _cbanque_mListeComptes
class _0RL_cd_be1b0533d67a6407_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_be1b0533d67a6407_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  banque::ListeComptes_var result;
};

void _0RL_cd_be1b0533d67a6407_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const banque::ListeComptes&) result >>= _n;

}

void _0RL_cd_be1b0533d67a6407_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new banque::ListeComptes;
  (banque::ListeComptes&)result <<= _n;

}

const char* const _0RL_cd_be1b0533d67a6407_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_be1b0533d67a6407_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_be1b0533d67a6407_40000000* tcd = (_0RL_cd_be1b0533d67a6407_40000000*)cd;
  banque::_impl_BanqueOperator* impl = (banque::_impl_BanqueOperator*) svnt->_ptrToInterface(banque::BanqueOperator::_PD_repoId);
  tcd->result = impl->listerComptes();


}

banque::ListeComptes* banque::_objref_BanqueOperator::listerComptes()
{
  _0RL_cd_be1b0533d67a6407_40000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_50000000, "listerComptes", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

banque::_pof_BanqueOperator::~_pof_BanqueOperator() {}


omniObjRef*
banque::_pof_BanqueOperator::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::banque::_objref_BanqueOperator(ior, id);
}


::CORBA::Boolean
banque::_pof_BanqueOperator::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::banque::BanqueOperator::_PD_repoId))
    return 1;
  
  return 0;
}

const banque::_pof_BanqueOperator _the_pof_banque_mBanqueOperator;

banque::_impl_BanqueOperator::~_impl_BanqueOperator() {}


::CORBA::Boolean
banque::_impl_BanqueOperator::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "getSolde")) {

    _0RL_cd_be1b0533d67a6407_00000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_10000000, "getSolde", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "effectuerOperation")) {

    _0RL_cd_be1b0533d67a6407_20000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_30000000, "effectuerOperation", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "listerComptes")) {

    _0RL_cd_be1b0533d67a6407_40000000 _call_desc(_0RL_lcfn_be1b0533d67a6407_50000000, "listerComptes", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
banque::_impl_BanqueOperator::_ptrToInterface(const char* id)
{
  if (id == ::banque::BanqueOperator::_PD_repoId)
    return (::banque::_impl_BanqueOperator*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::banque::BanqueOperator::_PD_repoId))
    return (::banque::_impl_BanqueOperator*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
banque::_impl_BanqueOperator::_mostDerivedRepoId()
{
  return ::banque::BanqueOperator::_PD_repoId;
}

POA_banque::BanqueOperator::~BanqueOperator() {}

