// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "banque.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



void
banque::Compte::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(titulaire,0);
  solde >>= _n;

}

void
banque::Compte::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  titulaire = _n.unmarshalString(0);
  (::CORBA::Double&)solde <<= _n;

}

::CORBA::Exception::insertExceptionToAny banque::ErreurBanque::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP banque::ErreurBanque::insertToAnyFnNCP = 0;

banque::ErreurBanque::ErreurBanque(const banque::ErreurBanque& _s) : ::CORBA::UserException(_s)
{
  message = _s.message;

}

banque::ErreurBanque::ErreurBanque(const char* _message)
{
  pd_insertToAnyFn    = banque::ErreurBanque::insertToAnyFn;
  pd_insertToAnyFnNCP = banque::ErreurBanque::insertToAnyFnNCP;
  message = _message;

}



banque::ErreurBanque& banque::ErreurBanque::operator=(const banque::ErreurBanque& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    message = _s.message;

  }
  return *this;
}

banque::ErreurBanque::~ErreurBanque() {}

void banque::ErreurBanque::_raise() const { throw *this; }

const char* banque::ErreurBanque::_PD_repoId = "IDL:banque/ErreurBanque:1.0";
const char* banque::ErreurBanque::_PD_typeId = "Exception/UserException/banque::ErreurBanque";

banque::ErreurBanque* banque::ErreurBanque::_downcast(::CORBA::Exception* _e) {
  return (ErreurBanque*) _NP_is_a(_e, _PD_typeId);
}

const banque::ErreurBanque* banque::ErreurBanque::_downcast(const ::CORBA::Exception* _e) {
  return (const ErreurBanque*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* banque::ErreurBanque::_NP_duplicate() const {
  return new ErreurBanque(*this);
}

const char* banque::ErreurBanque::_NP_typeId() const {
  return _PD_typeId;
}

const char* banque::ErreurBanque::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:banque/ErreurBanque:1.0");
  return _PD_repoId;
}
 
void banque::ErreurBanque::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
banque::ErreurBanque::operator>>= (cdrStream& _n) const
{
  _n.marshalString(message,0);

}

void
banque::ErreurBanque::operator<<= (cdrStream& _n)
{
  message = _n.unmarshalString(0);

}

banque::Audit_ptr banque::Audit_Helper::_nil() {
  return ::banque::Audit::_nil();
}

::CORBA::Boolean banque::Audit_Helper::is_nil(::banque::Audit_ptr p) {
  return ::CORBA::is_nil(p);

}

void banque::Audit_Helper::release(::banque::Audit_ptr p) {
  ::CORBA::release(p);
}

void banque::Audit_Helper::marshalObjRef(::banque::Audit_ptr obj, cdrStream& s) {
  ::banque::Audit::_marshalObjRef(obj, s);
}

banque::Audit_ptr banque::Audit_Helper::unmarshalObjRef(cdrStream& s) {
  return ::banque::Audit::_unmarshalObjRef(s);
}

void banque::Audit_Helper::duplicate(::banque::Audit_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

banque::Audit_ptr
banque::Audit::_duplicate(::banque::Audit_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

banque::Audit_ptr
banque::Audit::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


banque::Audit_ptr
banque::Audit::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

banque::Audit_ptr
banque::Audit::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Audit _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Audit* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Audit;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* banque::Audit::_PD_repoId = "IDL:banque/Audit:1.0";


banque::_objref_Audit::~_objref_Audit() {
  
}


banque::_objref_Audit::_objref_Audit(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::banque::Audit::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
banque::_objref_Audit::_ptrToObjRef(const char* id)
{
  if (id == ::banque::Audit::_PD_repoId)
    return (::banque::Audit_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::banque::Audit::_PD_repoId))
    return (::banque::Audit_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for banque::Audit::journaliser

// Proxy call descriptor class. Mangled signature:
//  _wvoid_i_cstring_i_cstring
class _0RL_cd_47311259eb31f6fa_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 1, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
};

void _0RL_cd_47311259eb31f6fa_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_47311259eb31f6fa_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

const char* const _0RL_cd_47311259eb31f6fa_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_00000000* tcd = (_0RL_cd_47311259eb31f6fa_00000000*)cd;
  banque::_impl_Audit* impl = (banque::_impl_Audit*) svnt->_ptrToInterface(banque::Audit::_PD_repoId);
  impl->journaliser(tcd->arg_0, tcd->arg_1);


}

void banque::_objref_Audit::journaliser(const char* operation, const char* details)
{
  _0RL_cd_47311259eb31f6fa_00000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_10000000, "journaliser", 12);
  _call_desc.arg_0 = operation;
  _call_desc.arg_1 = details;

  _invoke(_call_desc);



}

banque::_pof_Audit::~_pof_Audit() {}


omniObjRef*
banque::_pof_Audit::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::banque::_objref_Audit(ior, id);
}


::CORBA::Boolean
banque::_pof_Audit::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::banque::Audit::_PD_repoId))
    return 1;
  
  return 0;
}

const banque::_pof_Audit _the_pof_banque_mAudit;

banque::_impl_Audit::~_impl_Audit() {}


::CORBA::Boolean
banque::_impl_Audit::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "journaliser")) {

    _0RL_cd_47311259eb31f6fa_00000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_10000000, "journaliser", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
banque::_impl_Audit::_ptrToInterface(const char* id)
{
  if (id == ::banque::Audit::_PD_repoId)
    return (::banque::_impl_Audit*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::banque::Audit::_PD_repoId))
    return (::banque::_impl_Audit*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
banque::_impl_Audit::_mostDerivedRepoId()
{
  return ::banque::Audit::_PD_repoId;
}

banque::ServiceBanque_ptr banque::ServiceBanque_Helper::_nil() {
  return ::banque::ServiceBanque::_nil();
}

::CORBA::Boolean banque::ServiceBanque_Helper::is_nil(::banque::ServiceBanque_ptr p) {
  return ::CORBA::is_nil(p);

}

void banque::ServiceBanque_Helper::release(::banque::ServiceBanque_ptr p) {
  ::CORBA::release(p);
}

void banque::ServiceBanque_Helper::marshalObjRef(::banque::ServiceBanque_ptr obj, cdrStream& s) {
  ::banque::ServiceBanque::_marshalObjRef(obj, s);
}

banque::ServiceBanque_ptr banque::ServiceBanque_Helper::unmarshalObjRef(cdrStream& s) {
  return ::banque::ServiceBanque::_unmarshalObjRef(s);
}

void banque::ServiceBanque_Helper::duplicate(::banque::ServiceBanque_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

banque::ServiceBanque_ptr
banque::ServiceBanque::_duplicate(::banque::ServiceBanque_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

banque::ServiceBanque_ptr
banque::ServiceBanque::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


banque::ServiceBanque_ptr
banque::ServiceBanque::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

banque::ServiceBanque_ptr
banque::ServiceBanque::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ServiceBanque _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ServiceBanque* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_ServiceBanque;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* banque::ServiceBanque::_PD_repoId = "IDL:banque/ServiceBanque:1.0";


banque::_objref_ServiceBanque::~_objref_ServiceBanque() {
  
}


banque::_objref_ServiceBanque::_objref_ServiceBanque(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::banque::ServiceBanque::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
banque::_objref_ServiceBanque::_ptrToObjRef(const char* id)
{
  if (id == ::banque::ServiceBanque::_PD_repoId)
    return (::banque::ServiceBanque_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::banque::ServiceBanque::_PD_repoId))
    return (::banque::ServiceBanque_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for banque::ServiceBanque::creerCompte

// Proxy call descriptor class. Mangled signature:
//  _clong_i_cstring_i_cdouble_e_cbanque_mErreurBanque
class _0RL_cd_47311259eb31f6fa_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_47311259eb31f6fa_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  arg_1 >>= _n;

}

void _0RL_cd_47311259eb31f6fa_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_47311259eb31f6fa_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_47311259eb31f6fa_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_47311259eb31f6fa_20000000::_user_exns[] = {
  banque::ErreurBanque::_PD_repoId
};

void _0RL_cd_47311259eb31f6fa_20000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::ErreurBanque::_PD_repoId)) {
    banque::ErreurBanque _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_20000000* tcd = (_0RL_cd_47311259eb31f6fa_20000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->creerCompte(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    tcd->result = impl->creerCompte(tcd->arg_0, tcd->arg_1);
  else {
    try {
      tcd->result = impl->creerCompte(tcd->arg_0, tcd->arg_1);
    }
    catch(banque::ErreurBanque& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Long banque::_objref_ServiceBanque::creerCompte(const char* titulaire, ::CORBA::Double soldeInitial)
{
  _0RL_cd_47311259eb31f6fa_20000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_30000000, "creerCompte", 12);
  _call_desc.arg_0 = titulaire;
  _call_desc.arg_1 = soldeInitial;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for banque::ServiceBanque::consulterSolde

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_clong_e_cbanque_mErreurBanque
class _0RL_cd_47311259eb31f6fa_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_47311259eb31f6fa_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_47311259eb31f6fa_40000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

void _0RL_cd_47311259eb31f6fa_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_47311259eb31f6fa_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_47311259eb31f6fa_40000000::_user_exns[] = {
  banque::ErreurBanque::_PD_repoId
};

void _0RL_cd_47311259eb31f6fa_40000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::ErreurBanque::_PD_repoId)) {
    banque::ErreurBanque _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_40000000* tcd = (_0RL_cd_47311259eb31f6fa_40000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->consulterSolde(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->consulterSolde(tcd->arg_0);
  else {
    try {
      tcd->result = impl->consulterSolde(tcd->arg_0);
    }
    catch(banque::ErreurBanque& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double banque::_objref_ServiceBanque::consulterSolde(::CORBA::Long idCompte)
{
  _0RL_cd_47311259eb31f6fa_40000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_50000000, "consulterSolde", 15);
  _call_desc.arg_0 = idCompte;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for banque::ServiceBanque::deposer

// Proxy call descriptor class. Mangled signature:
//  void_i_clong_i_cdouble_e_cbanque_mErreurBanque
class _0RL_cd_47311259eb31f6fa_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Double arg_1;
};

void _0RL_cd_47311259eb31f6fa_60000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_47311259eb31f6fa_60000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

const char* const _0RL_cd_47311259eb31f6fa_60000000::_user_exns[] = {
  banque::ErreurBanque::_PD_repoId
};

void _0RL_cd_47311259eb31f6fa_60000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::ErreurBanque::_PD_repoId)) {
    banque::ErreurBanque _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_60000000* tcd = (_0RL_cd_47311259eb31f6fa_60000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  impl->deposer(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    impl->deposer(tcd->arg_0, tcd->arg_1);
  else {
    try {
      impl->deposer(tcd->arg_0, tcd->arg_1);
    }
    catch(banque::ErreurBanque& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void banque::_objref_ServiceBanque::deposer(::CORBA::Long idCompte, ::CORBA::Double montant)
{
  _0RL_cd_47311259eb31f6fa_60000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_70000000, "deposer", 8);
  _call_desc.arg_0 = idCompte;
  _call_desc.arg_1 = montant;

  _invoke(_call_desc);



}


//
// Code for banque::ServiceBanque::retirer

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_60000000* tcd = (_0RL_cd_47311259eb31f6fa_60000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  impl->retirer(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    impl->retirer(tcd->arg_0, tcd->arg_1);
  else {
    try {
      impl->retirer(tcd->arg_0, tcd->arg_1);
    }
    catch(banque::ErreurBanque& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void banque::_objref_ServiceBanque::retirer(::CORBA::Long idCompte, ::CORBA::Double montant)
{
  _0RL_cd_47311259eb31f6fa_60000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_80000000, "retirer", 8);
  _call_desc.arg_0 = idCompte;
  _call_desc.arg_1 = montant;

  _invoke(_call_desc);



}


//
// Code for banque::ServiceBanque::virement

// Proxy call descriptor class. Mangled signature:
//  void_i_clong_i_clong_i_cdouble_e_cbanque_mErreurBanque
class _0RL_cd_47311259eb31f6fa_90000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_90000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Double arg_2;
};

void _0RL_cd_47311259eb31f6fa_90000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_47311259eb31f6fa_90000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;
  (::CORBA::Double&)arg_2 <<= _n;

}

const char* const _0RL_cd_47311259eb31f6fa_90000000::_user_exns[] = {
  banque::ErreurBanque::_PD_repoId
};

void _0RL_cd_47311259eb31f6fa_90000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, banque::ErreurBanque::_PD_repoId)) {
    banque::ErreurBanque _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_90000000* tcd = (_0RL_cd_47311259eb31f6fa_90000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  impl->virement(tcd->arg_0, tcd->arg_1, tcd->arg_2);
#else
  if (!cd->is_upcall())
    impl->virement(tcd->arg_0, tcd->arg_1, tcd->arg_2);
  else {
    try {
      impl->virement(tcd->arg_0, tcd->arg_1, tcd->arg_2);
    }
    catch(banque::ErreurBanque& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void banque::_objref_ServiceBanque::virement(::CORBA::Long source, ::CORBA::Long destination, ::CORBA::Double montant)
{
  _0RL_cd_47311259eb31f6fa_90000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_a0000000, "virement", 9);
  _call_desc.arg_0 = source;
  _call_desc.arg_1 = destination;
  _call_desc.arg_2 = montant;

  _invoke(_call_desc);



}


//
// Code for banque::ServiceBanque::listerComptes

// Proxy call descriptor class. Mangled signature:
//  _cbanque_mListeComptes
class _0RL_cd_47311259eb31f6fa_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_47311259eb31f6fa_b0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  banque::ListeComptes_var result;
};

void _0RL_cd_47311259eb31f6fa_b0000000::marshalReturnedValues(cdrStream& _n)
{
  (const banque::ListeComptes&) result >>= _n;

}

void _0RL_cd_47311259eb31f6fa_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new banque::ListeComptes;
  (banque::ListeComptes&)result <<= _n;

}

const char* const _0RL_cd_47311259eb31f6fa_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_47311259eb31f6fa_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_47311259eb31f6fa_b0000000* tcd = (_0RL_cd_47311259eb31f6fa_b0000000*)cd;
  banque::_impl_ServiceBanque* impl = (banque::_impl_ServiceBanque*) svnt->_ptrToInterface(banque::ServiceBanque::_PD_repoId);
  tcd->result = impl->listerComptes();


}

banque::ListeComptes* banque::_objref_ServiceBanque::listerComptes()
{
  _0RL_cd_47311259eb31f6fa_b0000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_c0000000, "listerComptes", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}

banque::_pof_ServiceBanque::~_pof_ServiceBanque() {}


omniObjRef*
banque::_pof_ServiceBanque::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::banque::_objref_ServiceBanque(ior, id);
}


::CORBA::Boolean
banque::_pof_ServiceBanque::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::banque::ServiceBanque::_PD_repoId))
    return 1;
  
  return 0;
}

const banque::_pof_ServiceBanque _the_pof_banque_mServiceBanque;

banque::_impl_ServiceBanque::~_impl_ServiceBanque() {}


::CORBA::Boolean
banque::_impl_ServiceBanque::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "creerCompte")) {

    _0RL_cd_47311259eb31f6fa_20000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_30000000, "creerCompte", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "consulterSolde")) {

    _0RL_cd_47311259eb31f6fa_40000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_50000000, "consulterSolde", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "deposer")) {

    _0RL_cd_47311259eb31f6fa_60000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_70000000, "deposer", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "retirer")) {

    _0RL_cd_47311259eb31f6fa_60000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_80000000, "retirer", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "virement")) {

    _0RL_cd_47311259eb31f6fa_90000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_a0000000, "virement", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "listerComptes")) {

    _0RL_cd_47311259eb31f6fa_b0000000 _call_desc(_0RL_lcfn_47311259eb31f6fa_c0000000, "listerComptes", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
banque::_impl_ServiceBanque::_ptrToInterface(const char* id)
{
  if (id == ::banque::ServiceBanque::_PD_repoId)
    return (::banque::_impl_ServiceBanque*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::banque::ServiceBanque::_PD_repoId))
    return (::banque::_impl_ServiceBanque*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
banque::_impl_ServiceBanque::_mostDerivedRepoId()
{
  return ::banque::ServiceBanque::_PD_repoId;
}

POA_banque::Audit::~Audit() {}

POA_banque::ServiceBanque::~ServiceBanque() {}

