// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "banque.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_3_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::PR_structMember _0RL_structmember_banque_mCompte[] = {
  {"id", CORBA::TypeCode::PR_long_tc()},
  {"titulaire", CORBA::TypeCode::PR_string_tc(0, &_0RL_tcTrack)},
  {"solde", CORBA::TypeCode::PR_double_tc()}
};

#ifdef _0RL_tc_banque_mCompte
#  undef _0RL_tc_banque_mCompte
#endif
static CORBA::TypeCode_ptr _0RL_tc_banque_mCompte = CORBA::TypeCode::PR_struct_tc("IDL:banque/Compte:1.0", "Compte", _0RL_structmember_banque_mCompte, 3, &_0RL_tcTrack);

#if defined(OMNI_HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_Compte = _0RL_tc_banque_mCompte;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_Compte = _0RL_tc_banque_mCompte;
#endif






static CORBA::TypeCode_ptr _0RL_tc_banque_mListeComptes = CORBA::TypeCode::PR_alias_tc("IDL:banque/ListeComptes:1.0", "ListeComptes", CORBA::TypeCode::PR_sequence_tc(0, _0RL_tc_banque_mCompte, &_0RL_tcTrack), &_0RL_tcTrack);


#if defined(OMNI_HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_ListeComptes = _0RL_tc_banque_mListeComptes;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_ListeComptes = _0RL_tc_banque_mListeComptes;
#endif

static CORBA::PR_structMember _0RL_structmember_banque_mErreurBanque[] = {
  {"message", CORBA::TypeCode::PR_string_tc(0, &_0RL_tcTrack)}
};

static CORBA::TypeCode_ptr _0RL_tc_banque_mErreurBanque = CORBA::TypeCode::PR_exception_tc("IDL:banque/ErreurBanque:1.0", "ErreurBanque", _0RL_structmember_banque_mErreurBanque, 1, &_0RL_tcTrack);
#if defined(OMNI_HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_ErreurBanque = _0RL_tc_banque_mErreurBanque;
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_ErreurBanque = _0RL_tc_banque_mErreurBanque;
#endif


#if defined(OMNI_HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_Audit = CORBA::TypeCode::PR_interface_tc("IDL:banque/Audit:1.0", "Audit", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_Audit = CORBA::TypeCode::PR_interface_tc("IDL:banque/Audit:1.0", "Audit", &_0RL_tcTrack);
#endif

#if defined(OMNI_HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace banque { 
  const ::CORBA::TypeCode_ptr _tc_ServiceBanque = CORBA::TypeCode::PR_interface_tc("IDL:banque/ServiceBanque:1.0", "ServiceBanque", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr banque::_tc_ServiceBanque = CORBA::TypeCode::PR_interface_tc("IDL:banque/ServiceBanque:1.0", "ServiceBanque", &_0RL_tcTrack);
#endif

static void _0RL_banque_mCompte_marshal_fn(cdrStream& _s, void* _v)
{
  banque::Compte* _p = (banque::Compte*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mCompte_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::Compte* _p = new banque::Compte;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mCompte_destructor_fn(void* _v)
{
  banque::Compte* _p = (banque::Compte*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::Compte& _s)
{
  banque::Compte* _p = new banque::Compte(_s);
  _a.PR_insert(_0RL_tc_banque_mCompte,
               _0RL_banque_mCompte_marshal_fn,
               _0RL_banque_mCompte_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, banque::Compte* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mCompte,
               _0RL_banque_mCompte_marshal_fn,
               _0RL_banque_mCompte_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::Compte*& _sp)
{
  return _a >>= (const banque::Compte*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::Compte*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mCompte,
                    _0RL_banque_mCompte_unmarshal_fn,
                    _0RL_banque_mCompte_marshal_fn,
                    _0RL_banque_mCompte_destructor_fn,
                    _v)) {
    _sp = (const banque::Compte*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_banque_mListeComptes_marshal_fn(cdrStream& _s, void* _v)
{
  banque::ListeComptes* _p = (banque::ListeComptes*)_v;
  *_p >>= _s;
}
static void _0RL_banque_mListeComptes_unmarshal_fn(cdrStream& _s, void*& _v)
{
  banque::ListeComptes* _p = new banque::ListeComptes;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mListeComptes_destructor_fn(void* _v)
{
  banque::ListeComptes* _p = (banque::ListeComptes*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::ListeComptes& _s)
{
  banque::ListeComptes* _p = new banque::ListeComptes(_s);
  _a.PR_insert(_0RL_tc_banque_mListeComptes,
               _0RL_banque_mListeComptes_marshal_fn,
               _0RL_banque_mListeComptes_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, banque::ListeComptes* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mListeComptes,
               _0RL_banque_mListeComptes_marshal_fn,
               _0RL_banque_mListeComptes_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::ListeComptes*& _sp)
{
  return _a >>= (const banque::ListeComptes*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::ListeComptes*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mListeComptes,
                    _0RL_banque_mListeComptes_unmarshal_fn,
                    _0RL_banque_mListeComptes_marshal_fn,
                    _0RL_banque_mListeComptes_destructor_fn,
                    _v)) {
    _sp = (const banque::ListeComptes*)_v;
    return 1;
  }
  return 0;
}


static void _0RL_banque_mErreurBanque_marshal_fn(cdrStream& _s, void* _v)
{
  const banque::ErreurBanque* _p = (const banque::ErreurBanque*)_v;
  ::CORBA::Any::PR_marshalExceptionRepoId(_s, _p->_rep_id());
  *_p >>= _s;
}
static void _0RL_banque_mErreurBanque_unmarshal_fn(cdrStream& _s, void*& _v)
{
  ::CORBA::Any::PR_unmarshalExceptionRepoId(_s);
  banque::ErreurBanque* _p = new banque::ErreurBanque;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_banque_mErreurBanque_destructor_fn(void* _v)
{
  banque::ErreurBanque* _p = (banque::ErreurBanque*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const banque::ErreurBanque& _s)
{
  banque::ErreurBanque* _p = new banque::ErreurBanque(_s);
  _a.PR_insert(_0RL_tc_banque_mErreurBanque,
               _0RL_banque_mErreurBanque_marshal_fn,
               _0RL_banque_mErreurBanque_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, const banque::ErreurBanque* _sp)
{
  _a.PR_insert(_0RL_tc_banque_mErreurBanque,
               _0RL_banque_mErreurBanque_marshal_fn,
               _0RL_banque_mErreurBanque_destructor_fn,
               (banque::ErreurBanque*)_sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const banque::ErreurBanque*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_banque_mErreurBanque,
                    _0RL_banque_mErreurBanque_unmarshal_fn,
                    _0RL_banque_mErreurBanque_marshal_fn,
                    _0RL_banque_mErreurBanque_destructor_fn,
                    _v)) {
    _sp = (const banque::ErreurBanque*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_insertToAny__cbanque_mErreurBanque(::CORBA::Any& _a, const ::CORBA::Exception& _e) {
  const banque::ErreurBanque & _ex = (const banque::ErreurBanque &) _e;
  operator<<=(_a,_ex);
}

static void _0RL_insertToAnyNCP__cbanque_mErreurBanque (::CORBA::Any& _a, const ::CORBA::Exception* _e) {
  const banque::ErreurBanque* _ex = (const banque::ErreurBanque*) _e;
  operator<<=(_a,_ex);
}

class _0RL_insertToAny_Singleton__cbanque_mErreurBanque {
public:
  _0RL_insertToAny_Singleton__cbanque_mErreurBanque() {
    banque::ErreurBanque::insertToAnyFn = _0RL_insertToAny__cbanque_mErreurBanque;
    banque::ErreurBanque::insertToAnyFnNCP = _0RL_insertToAnyNCP__cbanque_mErreurBanque;
  }
};
static _0RL_insertToAny_Singleton__cbanque_mErreurBanque _0RL_insertToAny_Singleton__cbanque_mErreurBanque_;

static void _0RL_banque_mAudit_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_banque_mAudit_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(banque::Audit::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_banque_mAudit_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, banque::Audit_ptr _o)
{
  banque::Audit_ptr _no = banque::Audit::_duplicate(_o);
  _a.PR_insert(banque::_tc_Audit,
               _0RL_banque_mAudit_marshal_fn,
               _0RL_banque_mAudit_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, banque::Audit_ptr* _op)
{
  _a.PR_insert(banque::_tc_Audit,
               _0RL_banque_mAudit_marshal_fn,
               _0RL_banque_mAudit_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = banque::Audit::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::Audit_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(banque::_tc_Audit,
                    _0RL_banque_mAudit_unmarshal_fn,
                    _0RL_banque_mAudit_marshal_fn,
                    _0RL_banque_mAudit_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (banque::Audit_ptr)_r->_ptrToObjRef(banque::Audit::_PD_repoId);
    else
      _o = banque::Audit::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_banque_mServiceBanque_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_banque_mServiceBanque_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(banque::ServiceBanque::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_banque_mServiceBanque_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, banque::ServiceBanque_ptr _o)
{
  banque::ServiceBanque_ptr _no = banque::ServiceBanque::_duplicate(_o);
  _a.PR_insert(banque::_tc_ServiceBanque,
               _0RL_banque_mServiceBanque_marshal_fn,
               _0RL_banque_mServiceBanque_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, banque::ServiceBanque_ptr* _op)
{
  _a.PR_insert(banque::_tc_ServiceBanque,
               _0RL_banque_mServiceBanque_marshal_fn,
               _0RL_banque_mServiceBanque_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = banque::ServiceBanque::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, banque::ServiceBanque_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(banque::_tc_ServiceBanque,
                    _0RL_banque_mServiceBanque_unmarshal_fn,
                    _0RL_banque_mServiceBanque_marshal_fn,
                    _0RL_banque_mServiceBanque_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (banque::ServiceBanque_ptr)_r->_ptrToObjRef(banque::ServiceBanque::_PD_repoId);
    else
      _o = banque::ServiceBanque::_nil();
    return 1;
  }
  return 0;
}

