package banque;


/**
* banque/_ServiceBanqueStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
public class _ServiceBanqueStub extends org.omg.CORBA.portable.ObjectImpl implements banque.ServiceBanque
{

  public int creerCompte (String titulaire, double soldeInitial) throws banque.ErreurBanque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerCompte", true);
                $out.write_string (titulaire);
                $out.write_double (soldeInitial);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:banque/ErreurBanque:1.0"))
                    throw banque.ErreurBanqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerCompte (titulaire, soldeInitial        );
            } finally {
                _releaseReply ($in);
            }
  } // creerCompte

  public double consulterSolde (int idCompte) throws banque.ErreurBanque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consulterSolde", true);
                $out.write_long (idCompte);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:banque/ErreurBanque:1.0"))
                    throw banque.ErreurBanqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consulterSolde (idCompte        );
            } finally {
                _releaseReply ($in);
            }
  } // consulterSolde

  public void deposer (int idCompte, double montant) throws banque.ErreurBanque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deposer", true);
                $out.write_long (idCompte);
                $out.write_double (montant);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:banque/ErreurBanque:1.0"))
                    throw banque.ErreurBanqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                deposer (idCompte, montant        );
            } finally {
                _releaseReply ($in);
            }
  } // deposer

  public void retirer (int idCompte, double montant) throws banque.ErreurBanque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("retirer", true);
                $out.write_long (idCompte);
                $out.write_double (montant);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:banque/ErreurBanque:1.0"))
                    throw banque.ErreurBanqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                retirer (idCompte, montant        );
            } finally {
                _releaseReply ($in);
            }
  } // retirer

  public void virement (int source, int destination, double montant) throws banque.ErreurBanque
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("virement", true);
                $out.write_long (source);
                $out.write_long (destination);
                $out.write_double (montant);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:banque/ErreurBanque:1.0"))
                    throw banque.ErreurBanqueHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                virement (source, destination, montant        );
            } finally {
                _releaseReply ($in);
            }
  } // virement

  public banque.Compte[] listerComptes ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerComptes", true);
                $in = _invoke ($out);
                banque.Compte $result[] = banque.ListeComptesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerComptes (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerComptes

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:banque/ServiceBanque:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "banque._ServiceBanqueStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServiceBanqueStub
