package banque;


/**
* banque/AuditHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// "oneway" : appel asynchrone, sans valeur de retour ni attente.
abstract public class AuditHelper
{
  private static String  _id = "IDL:banque/Audit:1.0";

  public static void insert (org.omg.CORBA.Any a, banque.Audit that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banque.Audit extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (banque.AuditHelper.id (), "Audit");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banque.Audit read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuditStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banque.Audit value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static banque.Audit narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.Audit)
      return (banque.Audit)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._AuditStub stub = new banque._AuditStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static banque.Audit unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.Audit)
      return (banque.Audit)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._AuditStub stub = new banque._AuditStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
