package banque;


/**
* banque/AuditOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// "oneway" : appel asynchrone, sans valeur de retour ni attente.
public interface AuditOperations 
{
  void journaliser (String operation, String details);
} // interface AuditOperations
