package banque;

/**
* banque/AuditHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// "oneway" : appel asynchrone, sans valeur de retour ni attente.
public final class AuditHolder implements org.omg.CORBA.portable.Streamable
{
  public banque.Audit value = null;

  public AuditHolder ()
  {
  }

  public AuditHolder (banque.Audit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banque.AuditHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banque.AuditHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banque.AuditHelper.type ();
  }

}
