package banque;


/**
* banque/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/

public final class Compte implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String titulaire = null;
  public double solde = (double)0;

  public Compte ()
  {
  } // ctor

  public Compte (int _id, String _titulaire, double _solde)
  {
    id = _id;
    titulaire = _titulaire;
    solde = _solde;
  } // ctor

} // class Compte
