package banque;

/**
* banque/ErreurBanqueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/

public final class ErreurBanqueHolder implements org.omg.CORBA.portable.Streamable
{
  public banque.ErreurBanque value = null;

  public ErreurBanqueHolder ()
  {
  }

  public ErreurBanqueHolder (banque.ErreurBanque initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banque.ErreurBanqueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banque.ErreurBanqueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banque.ErreurBanqueHelper.type ();
  }

}
