package banque;


/**
* banque/ErreurBanque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/

public final class ErreurBanque extends org.omg.CORBA.UserException
{
  public String message = null;

  public ErreurBanque ()
  {
    super(ErreurBanqueHelper.id());
  } // ctor

  public ErreurBanque (String _message)
  {
    super(ErreurBanqueHelper.id());
    message = _message;
  } // ctor


  public ErreurBanque (String $reason, String _message)
  {
    super(ErreurBanqueHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ErreurBanque
