package banque;


/**
* banque/ListeComptesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/

public final class ListeComptesHolder implements org.omg.CORBA.portable.Streamable
{
  public banque.Compte value[] = null;

  public ListeComptesHolder ()
  {
  }

  public ListeComptesHolder (banque.Compte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banque.ListeComptesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banque.ListeComptesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banque.ListeComptesHelper.type ();
  }

}
