package banque;


/**
* banque/ServiceBanque.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
public interface ServiceBanque extends ServiceBanqueOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceBanque
