package banque;


/**
* banque/ServiceBanqueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
public interface ServiceBanqueOperations 
{
  int creerCompte (String titulaire, double soldeInitial) throws banque.ErreurBanque;
  double consulterSolde (int idCompte) throws banque.ErreurBanque;
  void deposer (int idCompte, double montant) throws banque.ErreurBanque;
  void retirer (int idCompte, double montant) throws banque.ErreurBanque;
  void virement (int source, int destination, double montant) throws banque.ErreurBanque;
  banque.Compte[] listerComptes ();
} // interface ServiceBanqueOperations
