package banque;


/**
* banque/ServiceBanquePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
public abstract class ServiceBanquePOA extends org.omg.PortableServer.Servant
 implements banque.ServiceBanqueOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerCompte", new java.lang.Integer (0));
    _methods.put ("consulterSolde", new java.lang.Integer (1));
    _methods.put ("deposer", new java.lang.Integer (2));
    _methods.put ("retirer", new java.lang.Integer (3));
    _methods.put ("virement", new java.lang.Integer (4));
    _methods.put ("listerComptes", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // banque/ServiceBanque/creerCompte
       {
         try {
           String titulaire = in.read_string ();
           double soldeInitial = in.read_double ();
           int $result = (int)0;
           $result = this.creerCompte (titulaire, soldeInitial);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (banque.ErreurBanque $ex) {
           out = $rh.createExceptionReply ();
           banque.ErreurBanqueHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // banque/ServiceBanque/consulterSolde
       {
         try {
           int idCompte = in.read_long ();
           double $result = (double)0;
           $result = this.consulterSolde (idCompte);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (banque.ErreurBanque $ex) {
           out = $rh.createExceptionReply ();
           banque.ErreurBanqueHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // banque/ServiceBanque/deposer
       {
         try {
           int idCompte = in.read_long ();
           double montant = in.read_double ();
           this.deposer (idCompte, montant);
           out = $rh.createReply();
         } catch (banque.ErreurBanque $ex) {
           out = $rh.createExceptionReply ();
           banque.ErreurBanqueHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // banque/ServiceBanque/retirer
       {
         try {
           int idCompte = in.read_long ();
           double montant = in.read_double ();
           this.retirer (idCompte, montant);
           out = $rh.createReply();
         } catch (banque.ErreurBanque $ex) {
           out = $rh.createExceptionReply ();
           banque.ErreurBanqueHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // banque/ServiceBanque/virement
       {
         try {
           int source = in.read_long ();
           int destination = in.read_long ();
           double montant = in.read_double ();
           this.virement (source, destination, montant);
           out = $rh.createReply();
         } catch (banque.ErreurBanque $ex) {
           out = $rh.createExceptionReply ();
           banque.ErreurBanqueHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // banque/ServiceBanque/listerComptes
       {
         banque.Compte $result[] = null;
         $result = this.listerComptes ();
         out = $rh.createReply();
         banque.ListeComptesHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:banque/ServiceBanque:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServiceBanque _this() 
  {
    return ServiceBanqueHelper.narrow(
    super._this_object());
  }

  public ServiceBanque _this(org.omg.CORBA.ORB orb) 
  {
    return ServiceBanqueHelper.narrow(
    super._this_object(orb));
  }


} // class ServiceBanquePOA
