package banque;


/**
* banque/ServiceBanqueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
abstract public class ServiceBanqueHelper
{
  private static String  _id = "IDL:banque/ServiceBanque:1.0";

  public static void insert (org.omg.CORBA.Any a, banque.ServiceBanque that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static banque.ServiceBanque extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (banque.ServiceBanqueHelper.id (), "ServiceBanque");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static banque.ServiceBanque read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServiceBanqueStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, banque.ServiceBanque value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static banque.ServiceBanque narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.ServiceBanque)
      return (banque.ServiceBanque)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._ServiceBanqueStub stub = new banque._ServiceBanqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static banque.ServiceBanque unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof banque.ServiceBanque)
      return (banque.ServiceBanque)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      banque._ServiceBanqueStub stub = new banque._ServiceBanqueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
