package banque;

/**
* banque/ServiceBanqueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/banque.idl
* mardi 22 septembre 2026 20 h 38 EAT
*/


// Service implémenté en C++, appelé par le client Java   (Java -> C++)
public final class ServiceBanqueHolder implements org.omg.CORBA.portable.Streamable
{
  public banque.ServiceBanque value = null;

  public ServiceBanqueHolder ()
  {
  }

  public ServiceBanqueHolder (banque.ServiceBanque initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = banque.ServiceBanqueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    banque.ServiceBanqueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return banque.ServiceBanqueHelper.type ();
  }

}
